
name: Flat
on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.5.2
      - name: Fetch data
        run: curl -e '${{ secrets.FETCH_URL }}' ${{ secrets.FETCH_URL }} -o readings/raw.json
      - name: Process data
        run: python readings/data_processor.py
      - name: Commit data
        run: |
          git config user.name "git-scraper"
          git config user.email "elliot.tormey+gitscraper@gmail.com"
          git add readings
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
