
name: Flat
on:
  push:
    paths:
      - .github/workflows/flat.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        run: |
          curl -e '${{ secrets.FETCH_URL }}' ${{ secrets.FETCH_URL }} -o readings.json
          cat readings.json
